version: '3.8'

services:
  # REST Endpoint
  rest_endpoint:
    build: 
      context: ./
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=nsdf_catalog_index
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ./:/app:Z    # This ensures, changes are picked up by the development server
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000


