version: '3.8'

services:
  # Backend REST
  backend_rest:
    build: 
      context: ./src/backend
    ports:
      - 5000:5000
    volumes:
      - ./src/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000


  # Backend DBMS
  # TODO
  #backend_dbms:
  #  build: ./src
  #  ports:
  #    - 9000:9000
  #  volumes:
  #    - ./src/dbms:/app
  #    - ./data/dbms:/data
  #  command: /bin/sh -c

  # Frontend
  frontend:
    build:
      context: ./src/frontend
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - './src/frontend:/app'
    command: /bin/sh -c "yarn && quasar dev"
