---
- name: Check if the SSL certs already exist
  stat:
    path: "{{ project_root_directory }}/{{ certbot_conf_directory }}/live/{{ hostname }}"
  become: true
  register: cert_path

- name: Install SSL certs if they don't already exist
  block:
    - name: Run docker-compose down
      docker_compose:
        project_src: "{{ project_root_directory }}/"
        state: absent

    - name: Generate the SSL Certs using Let's Encrypt and CertBot
      docker_container:
        name: certbot
        state: started
        image: certbot/certbot
        interactive: true
        detach: false
        auto_remove: true
        ports:
          - 80:80
        volumes:
          - "{{ project_root_directory }}/{{ certbot_conf_directory }}:/etc/letsencrypt"
          - "{{ project_root_directory }}/{{ certbot_www_directory }}:/var/www/certbot"
        command: |
          certonly --standalone --email kcoakley@sdsc.edu -d {{ hostname }}
          --rsa-key-size 4096 --agree-tos --no-eff-email --non-interactive
  when: not cert_path.stat.exists
