


run: setup
	quasar dev

deploy:
	#todo


setup: dependencies

dependencies:
	yarn install






update-icons:
	icongenie generate -m spa -i ./src/assets/nsdf/logo.png





distclean:
	sudo rm -rf node_modules
